//! `corescout-mcp`: the bridge an AI talks to.
//!
//! # A thin process on purpose
//!
//! Every MCP client starts its servers as child processes, so this one is
//! started and stopped constantly and may have several copies running at once.
//! It therefore holds no state, learns nothing, and owns no files: it forwards
//! to the service, which is the single thing that does.
//!
//! # Starting the service if it is not there
//!
//! Someone can connect their AI before opening the CoreScout window, and
//! failing at that point would make CoreScout look broken on the first thing
//! anyone tries. So a missing service is started, once, and waited for
//! briefly. If it cannot be started, the tools still list and each one returns
//! an explanation rather than a transport error, because a model that is told
//! "CoreScout is not running" can say so to the user.
//!
//! # Nothing is written to stdout but protocol
//!
//! stdout is the transport. Every diagnostic goes to stderr, because one
//! stray line on stdout desynchronises the client for the rest of the session.

use std::io::{BufReader, Write};
use std::time::{Duration, Instant};

use corescout_mcp_server::{Backend, Server};
use corescout_product_api::endpoint::Endpoint;
use corescout_product_api::Client;
use serde_json::Value;

/// How long to wait for a service that has just been started.
const STARTUP: Duration = Duration::from_secs(10);

const USAGE: &str = "\
corescout-mcp - CoreScout as a Model Context Protocol server

USAGE:
    corescout-mcp [OPTIONS]

This speaks MCP over stdin and stdout. It is meant to be started by an AI
client rather than run by hand.

OPTIONS:
    --no-start     Do not start the CoreScout service if it is not running
    -h, --help     Show this help

To connect it, open CoreScout and use the AI screen, which generates the exact
configuration for the client you are using.
";

fn main() -> std::process::ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.iter().any(|a| a == "-h" || a == "--help") {
        print!("{USAGE}");
        return std::process::ExitCode::SUCCESS;
    }
    let may_start = !args.iter().any(|a| a == "--no-start");

    let bridge = Bridge::connect(may_start);
    let mut server = Server::new(bridge);
    let stdin = std::io::stdin();
    let stdout = std::io::stdout();
    match server.run(BufReader::new(stdin.lock()), stdout.lock()) {
        Ok(()) => std::process::ExitCode::SUCCESS,
        Err(error) => {
            let _ = writeln!(std::io::stderr(), "corescout-mcp: {error}");
            std::process::ExitCode::FAILURE
        }
    }
}

/// Forwards tool calls to the service.
struct Bridge {
    client: Option<Client>,
}

impl Bridge {
    fn connect(may_start: bool) -> Bridge {
        if let Ok(client) = Client::connect() {
            if client.is_alive() {
                return Bridge {
                    client: Some(client),
                };
            }
        }
        if !may_start {
            return Bridge { client: None };
        }
        match start_service() {
            Ok(()) => Bridge {
                client: wait_for_service(),
            },
            Err(message) => {
                let _ = writeln!(std::io::stderr(), "corescout-mcp: {message}");
                Bridge { client: None }
            }
        }
    }
}

impl Backend for Bridge {
    fn call(&self, method: &str, params: &Value) -> Result<Value, String> {
        let Some(client) = &self.client else {
            return Err(NOT_RUNNING.into());
        };
        client
            .call(method, params.clone())
            .map_err(|error| error.to_string())
    }

    fn instructions(&self) -> String {
        match &self.client {
            // Generated by the service from its live state, so it never
            // advertises a mode that is not in force or a capability that is
            // switched off.
            Some(client) => client
                .call("briefing", serde_json::json!({}))
                .ok()
                .and_then(|value| {
                    value
                        .get("briefing")
                        .and_then(Value::as_str)
                        .map(str::to_string)
                })
                .unwrap_or_else(|| NOT_RUNNING.into()),
            None => NOT_RUNNING.into(),
        }
    }
}

/// What to say when there is nothing to forward to.
///
/// Written for a model to read out to a user, because that is what will happen
/// with it.
const NOT_RUNNING: &str = "CoreScout is installed but its service is not running, so it has \
                           nothing to tell you right now. Opening the CoreScout app will start \
                           it. Nothing else is affected.";

/// Start the service alongside this executable.
fn start_service() -> Result<(), String> {
    let exe = std::env::current_exe().map_err(|error| format!("cannot find myself: {error}"))?;
    let directory = exe
        .parent()
        .ok_or_else(|| "cannot find my own folder".to_string())?;
    let service = directory.join(if cfg!(windows) {
        "corescout-service.exe"
    } else {
        "corescout-service"
    });
    if !service.exists() {
        return Err(format!(
            "{} is not installed next to this bridge",
            service.display()
        ));
    }
    let mut command = std::process::Command::new(&service);
    command
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null());
    detach(&mut command);
    command
        .spawn()
        .map(|_| ())
        .map_err(|error| format!("could not start the CoreScout service: {error}"))
}

/// Start the service without a console window and without it dying with us.
///
/// An MCP client kills its servers when a session ends. Without this the
/// service would be started by the first agent session and stopped by it, so a
/// user would find CoreScout had forgotten everything between conversations.
#[cfg(windows)]
fn detach(command: &mut std::process::Command) {
    use std::os::windows::process::CommandExt;
    const DETACHED_PROCESS: u32 = 0x0000_0008;
    const CREATE_NEW_PROCESS_GROUP: u32 = 0x0000_0200;
    const CREATE_NO_WINDOW: u32 = 0x0800_0000;
    command.creation_flags(DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW);
}

#[cfg(not(windows))]
fn detach(_command: &mut std::process::Command) {}

/// Wait briefly for a service that has just been started.
fn wait_for_service() -> Option<Client> {
    let deadline = Instant::now() + STARTUP;
    while Instant::now() < deadline {
        if Endpoint::discover().is_ok() {
            if let Ok(client) = Client::connect() {
                if client.is_alive() {
                    return Some(client);
                }
            }
        }
        std::thread::sleep(Duration::from_millis(100));
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_bridge_with_nothing_to_forward_to_explains_itself_to_the_model() {
        // Not a transport error. A model that reads this can tell the user
        // what to do; one that gets a broken pipe cannot.
        let bridge = Bridge { client: None };
        let error = bridge
            .call("status", &serde_json::json!({}))
            .expect_err("should fail");
        assert!(error.contains("not running"), "{error}");
        assert!(error.contains("CoreScout app"), "{error}");
        assert!(bridge.instructions().contains("Nothing else is affected"));
    }

    #[test]
    fn the_protocol_still_works_with_no_service_behind_it() {
        // The failure mode that matters: an agent connects, CoreScout is not
        // running, and the client must still complete a handshake and list
        // tools rather than reporting a broken server.
        let mut server = Server::new(Bridge { client: None });
        let handshake = server
            .handle_line(r#"{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}"#)
            .expect("a reply");
        assert!(handshake.contains("protocolVersion"), "{handshake}");

        let listed = server
            .handle_line(r#"{"jsonrpc":"2.0","id":2,"method":"tools/list"}"#)
            .expect("a reply");
        assert!(listed.contains("corescout_ask"), "{listed}");

        let called = server
            .handle_line(
                r#"{"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"corescout_status","arguments":{}}}"#,
            )
            .expect("a reply");
        let reply: Value = serde_json::from_str(&called).expect("JSON");
        assert!(
            reply["error"].is_null(),
            "a tool failure is not a transport failure"
        );
        assert_eq!(reply["result"]["isError"], true);
    }

    #[test]
    fn the_service_is_looked_for_next_to_this_executable() {
        // Installed side by side. Looking on the path instead would find a
        // different build if someone has one, which is exactly the confusing
        // failure this avoids.
        let error = start_service().unwrap_err_or_default();
        // In a test binary there is no service next to us, so this is the
        // expected message rather than a failure of the test.
        assert!(
            error.contains("not installed next to") || error.contains("could not start"),
            "{error}"
        );
    }

    /// A small helper so the test above reads as one line.
    trait OrDefault {
        fn unwrap_err_or_default(self) -> String;
    }

    impl OrDefault for Result<(), String> {
        fn unwrap_err_or_default(self) -> String {
            self.err().unwrap_or_default()
        }
    }
}
